In [1]:
import numpy as np
import pandas as pd

In [3]:
file_path = 'load\share_dataset\satellite\satellite_party0_test.csv'

In [36]:
#load only the first 1000 rows
df = pd.read_csv(file_path, nrows=10, header=0 , delimiter=',' , dtype='int16')

In [37]:
#print df size in Mb
print(df.memory_usage(index=True).sum() / 1024**2)

6.190116882324219

In [38]:
# drop id make y an int and all other columns floats with 1 decimal points to save storage
df = df.drop(columns=['id'])

In [39]:
print(df.memory_usage(index=True).sum() / 1024**2)

6.190097808837891

In [48]:
df

,y,x0,x1,x2,x3,x4,x5,x6,x7,x8,...,x324522,x324523,x324524,x324525,x324526,x324527,x324528,x324529,x324530,x324531
0,2,65,65,65,65,65,65,65,65,65,...,38,38,38,37,37,38,38,39,39,39
1,3,97,97,97,102,102,102,102,102,101,...,171,171,174,175,175,175,175,173,173,173
2,3,77,77,78,78,78,78,78,78,78,...,142,145,145,144,144,148,148,153,153,153
3,3,94,94,94,94,91,91,91,91,91,...,35,39,38,67,68,88,88,111,111,92
4,0,200,200,200,200,200,200,200,200,200,...,75,76,76,77,77,76,76,76,76,76
5,2,66,66,66,66,66,66,67,67,67,...,42,40,35,35,29,29,34,34,33,33
6,2,81,81,81,79,79,79,79,79,79,...,77,69,72,93,92,92,91,73,73,78
7,2,156,155,155,155,155,155,154,146,147,...,11,11,11,12,12,12,12,13,13,12
8,3,51,52,52,52,52,52,52,52,52,...,35,35,26,26,20,20,22,22,28,28
9,3,98,98,98,98,98,98,101,102,102,...,197,196,193,193,195,192,193,200,200,204